=begin
#API（証拠金取引所）

#本APIを利用することにより、取り扱っている銘柄一覧の取得、ローソク足データの取得、板の取得、歩値の取得、注文、残高照会といった操作を行う事ができます。 ## 留意事項 - APIキーはお客様のアカウント情報と紐付いております。もし第三者がお客様のAPIキーを知った場合、遠隔で売買注文の操作が可能となります。APIキーを第三者へ渡す事はセキュリティリスクを鑑みお控えください。 - 他社が提供するAPI機能を使用した自動売買取引ツールは、ご自身の判断と責任でご利用ください。 - リクエストパラメーターやレスポンスの日時についてはミリ秒のtimestamp(Unix Time)を用います。 - 日時の範囲検索は「以上・未満」で検索します。 

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.54
=end

# Common files
require 'rakuten_trading/api_client'
require 'rakuten_trading/api_error'
require 'rakuten_trading/version'
require 'rakuten_trading/configuration'

# Models
require 'rakuten_trading/models/cfd_order_body'
require 'rakuten_trading/models/cfd_order_body_1'
require 'rakuten_trading/models/cfd_trade'
require 'rakuten_trading/models/inline_response_200'
require 'rakuten_trading/models/inline_response_200_1'
require 'rakuten_trading/models/inline_response_200_1_candlesticks'
require 'rakuten_trading/models/inline_response_200_2'
require 'rakuten_trading/models/inline_response_200_3'
require 'rakuten_trading/models/inline_response_200_4'
require 'rakuten_trading/models/inline_response_200_5'
require 'rakuten_trading/models/inline_response_200_6'
require 'rakuten_trading/models/inline_response_200_7'
require 'rakuten_trading/models/order'
require 'rakuten_trading/models/order_data'
require 'rakuten_trading/models/order_detail'
require 'rakuten_trading/models/order_response'
require 'rakuten_trading/models/trade'

# APIs
require 'rakuten_trading/api/private_api'
require 'rakuten_trading/api/public_api'

module RakutenTrading
  class << self
    # Customize default settings for the SDK using block.
    #   RakutenTrading.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
